import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdatePostContentNullable1763913766900 implements MigrationInterface {
    name = 'UpdatePostContentNullable1763913766900'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "temporary_posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text NOT NULL, "status" varchar(20) NOT NULL, "scheduled_time" datetime, "posted_time" datetime, "category_id" integer, "prompt_id" integer, "slot_id" integer, "parent_post_id" integer, "thread_position" integer NOT NULL DEFAULT (0), "external_id" varchar(50), "media_url" varchar(500), "retry_count" integer NOT NULL DEFAULT (0), "error_message" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_979fb4c9d38af5cb74829ab9a4f" FOREIGN KEY ("parent_post_id") REFERENCES "posts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_70e90674b4ef3ba731cb61f18c2" FOREIGN KEY ("slot_id") REFERENCES "schedule_slots" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_ffccdfa9e9247f6b3ad8bcdc764" FOREIGN KEY ("prompt_id") REFERENCES "prompts" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_852f266adc5d67c40405c887b49" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_posts"("id", "content", "status", "scheduled_time", "posted_time", "category_id", "prompt_id", "slot_id", "parent_post_id", "thread_position", "external_id", "media_url", "retry_count", "error_message", "created_at", "updated_at") SELECT "id", "content", "status", "scheduled_time", "posted_time", "category_id", "prompt_id", "slot_id", "parent_post_id", "thread_position", "external_id", "media_url", "retry_count", "error_message", "created_at", "updated_at" FROM "posts"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`ALTER TABLE "temporary_posts" RENAME TO "posts"`);
        await queryRunner.query(`CREATE TABLE "temporary_posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text, "status" varchar(20) NOT NULL, "scheduled_time" datetime, "posted_time" datetime, "category_id" integer, "prompt_id" integer, "slot_id" integer, "parent_post_id" integer, "thread_position" integer NOT NULL DEFAULT (0), "external_id" varchar(50), "media_url" varchar(500), "retry_count" integer NOT NULL DEFAULT (0), "error_message" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_979fb4c9d38af5cb74829ab9a4f" FOREIGN KEY ("parent_post_id") REFERENCES "posts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_70e90674b4ef3ba731cb61f18c2" FOREIGN KEY ("slot_id") REFERENCES "schedule_slots" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_ffccdfa9e9247f6b3ad8bcdc764" FOREIGN KEY ("prompt_id") REFERENCES "prompts" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_852f266adc5d67c40405c887b49" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "temporary_posts"("id", "content", "status", "scheduled_time", "posted_time", "category_id", "prompt_id", "slot_id", "parent_post_id", "thread_position", "external_id", "media_url", "retry_count", "error_message", "created_at", "updated_at") SELECT "id", "content", "status", "scheduled_time", "posted_time", "category_id", "prompt_id", "slot_id", "parent_post_id", "thread_position", "external_id", "media_url", "retry_count", "error_message", "created_at", "updated_at" FROM "posts"`);
        await queryRunner.query(`DROP TABLE "posts"`);
        await queryRunner.query(`ALTER TABLE "temporary_posts" RENAME TO "posts"`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "posts" RENAME TO "temporary_posts"`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text NOT NULL, "status" varchar(20) NOT NULL, "scheduled_time" datetime, "posted_time" datetime, "category_id" integer, "prompt_id" integer, "slot_id" integer, "parent_post_id" integer, "thread_position" integer NOT NULL DEFAULT (0), "external_id" varchar(50), "media_url" varchar(500), "retry_count" integer NOT NULL DEFAULT (0), "error_message" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_979fb4c9d38af5cb74829ab9a4f" FOREIGN KEY ("parent_post_id") REFERENCES "posts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_70e90674b4ef3ba731cb61f18c2" FOREIGN KEY ("slot_id") REFERENCES "schedule_slots" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_ffccdfa9e9247f6b3ad8bcdc764" FOREIGN KEY ("prompt_id") REFERENCES "prompts" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_852f266adc5d67c40405c887b49" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "posts"("id", "content", "status", "scheduled_time", "posted_time", "category_id", "prompt_id", "slot_id", "parent_post_id", "thread_position", "external_id", "media_url", "retry_count", "error_message", "created_at", "updated_at") SELECT "id", "content", "status", "scheduled_time", "posted_time", "category_id", "prompt_id", "slot_id", "parent_post_id", "thread_position", "external_id", "media_url", "retry_count", "error_message", "created_at", "updated_at" FROM "temporary_posts"`);
        await queryRunner.query(`DROP TABLE "temporary_posts"`);
        await queryRunner.query(`ALTER TABLE "posts" RENAME TO "temporary_posts"`);
        await queryRunner.query(`CREATE TABLE "posts" ("id" integer PRIMARY KEY AUTOINCREMENT NOT NULL, "content" text NOT NULL, "status" varchar(20) NOT NULL, "scheduled_time" datetime, "posted_time" datetime, "category_id" integer, "prompt_id" integer, "slot_id" integer, "parent_post_id" integer, "thread_position" integer NOT NULL DEFAULT (0), "external_id" varchar(50), "media_url" varchar(500), "retry_count" integer NOT NULL DEFAULT (0), "error_message" text, "created_at" datetime NOT NULL DEFAULT (datetime('now')), "updated_at" datetime NOT NULL DEFAULT (datetime('now')), CONSTRAINT "FK_979fb4c9d38af5cb74829ab9a4f" FOREIGN KEY ("parent_post_id") REFERENCES "posts" ("id") ON DELETE CASCADE ON UPDATE NO ACTION, CONSTRAINT "FK_70e90674b4ef3ba731cb61f18c2" FOREIGN KEY ("slot_id") REFERENCES "schedule_slots" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_ffccdfa9e9247f6b3ad8bcdc764" FOREIGN KEY ("prompt_id") REFERENCES "prompts" ("id") ON DELETE SET NULL ON UPDATE NO ACTION, CONSTRAINT "FK_852f266adc5d67c40405c887b49" FOREIGN KEY ("category_id") REFERENCES "categories" ("id") ON DELETE SET NULL ON UPDATE NO ACTION)`);
        await queryRunner.query(`INSERT INTO "posts"("id", "content", "status", "scheduled_time", "posted_time", "category_id", "prompt_id", "slot_id", "parent_post_id", "thread_position", "external_id", "media_url", "retry_count", "error_message", "created_at", "updated_at") SELECT "id", "content", "status", "scheduled_time", "posted_time", "category_id", "prompt_id", "slot_id", "parent_post_id", "thread_position", "external_id", "media_url", "retry_count", "error_message", "created_at", "updated_at" FROM "temporary_posts"`);
        await queryRunner.query(`DROP TABLE "temporary_posts"`);
    }

}
